apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend-feed
  namespace: default
  labels:
    app:  backend-feed
spec:
  selector:
    matchLabels:
      app: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        app:  backend-feed
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  backend-feed
        image:  designerseyi12345/udagram-api-feed:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1.5Gi"
            cpu: "500m"  
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_USERNAME

        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_HOST             

        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: POSTGRES_DB         

        - name: DB_DIALECT
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: DB_DIALECT  

        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_REGION 

        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_PROFILE 

        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: AWS_BUCKET 

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD 

        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: JWT_SECRET 

        - name: aws_access_key_id
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_access_key_id 

        - name: aws_secret_access_key
          valueFrom:
            secretKeyRef:
              name: aws-secret
              key: aws_secret_access_key 

        


        ports:
        - containerPort:  8080
          name:  backend-feed
      restartPolicy: Always