# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: default
type: Opaque
data:
  aws_access_key_id : QUtJQTNYVUlJVEpHVEhDTkpXWVMK
  aws_secret_access_key : VGJzci90elJkRFVwY2x1d2l0UFNDVGFYZVM5cldFRnJSVWNIVHJpTgo=


