apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend
  namespace: default
  labels:
    app:  frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app:  frontend
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  bfrontend
        image:  designerseyi12345/udagram-frontend
        resources:
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 8100
          
        ports:
        - containerPort:  8100
          name:  backend-feed
      restartPolicy: Always